Derivative.create!(symbol: 'AAPL', name: 'Apple')
Derivative.create!(symbol: 'MSFT', name: 'Microsoft')
Derivative.create!(symbol: 'GOOG', name: 'Google')
Derivative.create!(symbol: "BARC.L", name: 'Barclays')
Derivative.create!(symbol: 'TWTR', name: 'Twitter')
Derivative.create!(symbol: 'FB', name: 'Facebook')
Derivative.create!(symbol: "SIE.DE", name: "Siemens")
